import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve('extensao');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));
const content = fs.readFileSync(path.join(root, 'content.js'), 'utf8');
const background = fs.readFileSync(path.join(root, 'background.js'), 'utf8');
const sidePanel = fs.readFileSync(path.join(root, 'sidepanel.js'), 'utf8');
const sidePanelCss = fs.readFileSync(path.join(root, 'sidepanel.css'), 'utf8');
const sidePanelHtml = fs.readFileSync(path.join(root, 'sidepanel.html'), 'utf8');
const bridge = fs.readFileSync(path.join(root, 'main_bridge.js'), 'utf8');
const planningUi = fs.readFileSync(path.join(root, 'planejamento', 'ui.js'), 'utf8');
const frequency = fs.readFileSync(path.join(root, 'frequencia', '2.js'), 'utf8');
const contentProgram = fs.readFileSync(path.join(root, 'conteudo', 'conteudo.js'), 'utf8');

assert.equal(manifest.version, '5.7.1');
assert.equal(manifest.action.default_popup, undefined, 'A ação não pode usar popup antigo');
assert.equal(manifest.side_panel.default_path, 'sidepanel.html');
assert.ok(manifest.permissions.includes('sidePanel'));
assert.ok(manifest.web_accessible_resources?.[0]?.resources.includes('main_bridge.js'));
assert.ok(fs.existsSync(path.join(root, 'sidepanel.html')));
assert.ok(fs.existsSync(path.join(root, 'sidepanel.js')));
assert.ok(sidePanelCss.length > 500, 'O painel lateral precisa ter seu CSS de interface incluso no pacote');
assert.match(background, /openPanelOnActionClick/);
assert.match(content, /SIAP_READ_CONTEXT/);
assert.match(sidePanel, /SIAP_REQUEST/);
assert.match(sidePanel, /PLANNING_PREPARE/);
assert.match(sidePanel, /FREQUENCY_START/);
assert.match(sidePanel, /CONTENT_START/);
assert.match(sidePanel, /PEI_COLLECT/);
assert.match(sidePanelHtml, /Aplicar próxima aula/);
assert.match(sidePanelHtml, /Reaproveitar aulas salvas/);
assert.match(sidePanelHtml, /Frequência automática/);
assert.match(sidePanelHtml, /Conteúdo programático/);
assert.match(sidePanelHtml, /PEI com IA/);
assert.match(bridge, /PLANNING_STORE/);
assert.match(bridge, /__SIAP_SAAS_HEADLESS__/);
assert.match(planningUi, /if \(window\.__SIAP_SAAS_HEADLESS__\) return;/);
assert.match(frequency, /if \(window\.__SIAP_SAAS_HEADLESS__\) return;/);
assert.match(contentProgram, /if \(window\.__SIAP_SAAS_HEADLESS__\) return;/);
assert.doesNotMatch(content, /await bootProtectedPage\(auth\)/, 'Não pode inicializar módulos dentro da página do SIAP');
assert.doesNotMatch(content, /await renderHeaderAuthButtons\(\)/, 'Não pode criar cabeçalho SiapAI no SIAP');

console.log('OK: v5.7.0 usa painel lateral nativo, expõe os módulos completos e não injeta painéis no SIAP.');
